apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd/bases/addons.kope.io_networkings.yaml
- rbac/role.yaml

bases:
- minimal/base/

namePrefix: kopeio-networking-
namespace: kopeio-networking-system

commonLabels:
  k8s-app: kopeio-networking-operator

patchesStrategicMerge:
- minimal/add-tolerations.yaml
