# permissions for end users to view networkings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networking-viewer-role
rules:
- apiGroups:
  - addons.kope.io
  resources:
  - networkings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.kope.io
  resources:
  - networkings/status
  verbs:
  - get
