
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator
rules:
- apiGroups:
  - addons.kope.io
  resources:
  - networkings
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.kope.io
  resources:
  - networkings/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: operator
  namespace: kopeio-networking-system
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resourceNames:
  - kopeio-networking-agent
  resources:
  - daemonsets
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
